'use strict';

const GAME_FIELD_ID = 'gameField';
const DELAY = 10;
const FOOD_DELAY = 2000;
const MAX_TTL = 25000;
const POPULATION_SIZE = 100;
const ELITISM = 10;
const MUTATION_RATE = 0.3;
const MUTATION_AMOUNT = 3;
const MAX_SEEKING_DISTANCE = 200;
const SECTORS_OF_VISION = 16;

const FOUND_FOOD_SCORE = 50;
const CLOSER_TO_FOOD_COEFFICIENT = 5;
const DEATH_SCORE = 0;
const CLOSE_TO_EDGE_SCORE = 25;
