'use strict';

const GAME_FIELD_ID = 'gameField';
const DELAY = 10;
const FOOD_DELAY = 2000;
const MAX_TTL = 25000;
const POPULATION_SIZE = 50;
const ELITISM = 5;
const MUTATION_RATE = 0.3;
const MUTATION_AMOUNT = 3;
const MAX_SEEKING_DISTANCE = 200;
const SECTORS_OF_VISION = 16;
const EDGE_DETECTION_DISTANCE = 20;
const EDGE_KILLING_DISTANCE = 0;

const FOUND_FOOD_SCORE = 50;
const CLOSE_TO_FOOD_SCORE = 0.05;
const DEATH_SCORE = 0;
const CLOSE_TO_EDGE_SCORE = 10;
